---
schemas:
  - models/circuit.yml
  - models/dcim.yml
  - models/ipam.yml
  - models/locations.yml
  - models/organizations.yml
  - models/routing.yml
  - models/security.yml
  - models/topology.yml
jinja2_transforms:
  - name: "device_cisco"
    description: "Template to generate startup configuration for Cisco devices"
    query: "device_info"
    template_path: "templates/device_cisco_config.tpl.j2"

  - name: "device_arista"
    description: "Template to generate startup configuration for Arista devices"
    query: "device_info"
    template_path: "templates/device_arista_config.tpl.j2"

  - name: "firewall_config"
    description: "Template to generate startup configuration for a Juniper SRX Firewall"
    query: "juniper_srx_config"
    template_path: "templates/juniper_srx_config.j2"

artifact_definitions:
  - name: "Startup Config for Cisco devices"
    artifact_name: "startup-config"
    parameters:
      device: "name__value"
    content_type: "text/plain"
    targets: "cisco_devices"
    transformation: "device_cisco"

  - name: "Startup Config for Arista devices"
    artifact_name: "startup-config"
    parameters:
      device: "name__value"
    content_type: "text/plain"
    targets: "arista_devices"
    transformation: "device_arista"

  - name: "Firewall config"
    artifact_name: "firewall-config"
    parameters:
      device: "name__value"
    content_type: "text/plain"
    targets: "firewall_devices"
    transformation: "firewall_config"

check_definitions:
  - name: "check_device_topology"
    class_name: "InfrahubCheckDeviceTopology"
    file_path: "checks/check_device_topology.py"
  - name: backbone_link_redundancy
    class_name: InfrahubCheckBackboneLinkRedundancy
    file_path: "checks/check_backbone_link_redundancy.py"