---
artifact_definitions:
  - name: "Openconfig Interface for Arista devices"
    artifact_name: "openconfig-interfaces"
    parameters:
      device: "name__value"
    content_type: "application/json"
    targets: "arista_devices"
    transformation: "OCInterfaces"

  - name: "Startup Config for Cisco devices"
    artifact_name: "startup-config"
    parameters:
      device: "name__value"
    content_type: "text/plain"
    targets: "cisco_devices"
    transformation: "device_cisco"

  - name: "Startup Config for Arista devices"
    artifact_name: "startup-config"
    parameters:
      device: "name__value"
    content_type: "text/plain"
    targets: "arista_devices"
    transformation: "device_arista"

  - name: "Firewall config"
    artifact_name: "firewall-config"
    parameters:
      device: "name__value"
    content_type: "text/plain"
    targets: "firewall_devices"
    transformation: "firewall_config"
