---
schemas:
  - models/circuit.yml
  - models/dcim.yml
  - models/ipam.yml
  - models/locations.yml
  - models/organizations.yml
  - models/routing.yml
  - models/security.yml
  - models/topology.yml